version: "3.0"
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=my_db
      - MYSQL_RANDOM_ROOT_PASSWORD=true
